# Default values for chart-template.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

commonLabels:
  app: forte-account
  project: forte-frontend
  tier: frontend
  component: web
  environment: dev

image:
  repository: 227185325630.dkr.ecr.eu-west-1.amazonaws.com/onetech-frontend/forte-account
  tag: v9.0.33-dev-c67f074c
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: "forte-account"
fullnameOverride: "forte-account"

service:
  type: ClusterIP
  name: http
  protocol: TCP
  port: 80
  targetPort: 8080

containerPorts:
  - name: http
    protocol: TCP
    containerPort: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: ingress
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite /(.*) /$1 break;
  hosts:
    - host: test-ci-forte-account.onedev.zone
      paths: ['/']

  tls:
    - secretName: one-dev-secret
      hosts:
        - test-ci-forte-account.onedev.zone

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 200m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
